
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - moree.tscuite.cdz
  resources:
  - boys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - moree.tscuite.cdz
  resources:
  - boys/finalizers
  verbs:
  - update
- apiGroups:
  - moree.tscuite.cdz
  resources:
  - boys/status
  verbs:
  - get
  - patch
  - update
