# permissions for end users to view boys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: boy-viewer-role
rules:
- apiGroups:
  - moree.tscuite.cdz
  resources:
  - boys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - moree.tscuite.cdz
  resources:
  - boys/status
  verbs:
  - get
