# permissions for end users to edit nginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-editor-role
rules:
- apiGroups:
  - tscuite.registry.cn-hangzhou.aliyuncs.com
  resources:
  - nginxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tscuite.registry.cn-hangzhou.aliyuncs.com
  resources:
  - nginxes/status
  verbs:
  - get
