name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Agent
      run: |
        sudo bash -c "echo '47.95.181.38 registry.cn-beijing.aliyuncs.com' >> /etc/hosts"
        cat /etc/hosts
        docker pull registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-server:1.8.3
#     - name: Run tests
#       uses: nick-invision/retry@v2
#       with:
#         timeout_seconds: 30
#         max_attempts: 30
#         #retry_on: timeout
#         command: docker pull registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-server:1.8.3
        

