name: dontai-devops-cp
on:
  push:
    branches:    
      - 'main'
jobs:
  run_if:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v1
      - name: Generate version file
        run: |
           git checkout -b pr@20220530@${{github.run_number}}
           git remote set-url origin --push --add 'https://${{ secrets.cdzGITHUB_TOKEN }}@github.com/tscuite/tscuite.git'
           git push --set-upstream origin pr@20220530@${{github.run_number}}
