name: main
on:
  push:
    branches:
      - main

jobs:
  init:
    name: Check Generated Code for Drift
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - uses: dorny/paths-filter@v2
        id: selefra
        with:
          filters: |
            terraform:
              - 'terraform/**/*'
            rules:
              - '.github/workflows/**/*'
              - '.github/scripts/**/*'

      - name: Terraform apply
        if: steps.selefra.outputs.terraform == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          bash .github/scripts/terraform.sh aws
          #terraform init
          #terraform plan -no-color
          #terraform validate -no-color
        continue-on-error: true

      - name: rules
        if: steps.selefra.outputs.rules == 'true'
        run: |
          #运行规则 selefra init
          bash .github/scripts/terraform.sh rules

