name: RELEASE

on:
  workflow_dispatch:
    inputs:
      os_version:
        required: true
        type: string
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ./build/
          key: ${{ runner.OS }}-py-cache-${{ hashFiles('**/README.md') }}
          restore-keys: |
            ${{ runner.OS }}-py-cache-
      - name: build encryption
        run: |
          mkdir build
          touch /build/123.txt
