name: RELEASE

on:
  release:
    types: [ created, edited ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - id: release
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          ID=`echo ${TAG_NAME##v}`
          echo "::set-output name=VERSION::$ID"
          echo "$env"
