name: check_generated_code_drift
on:
  push:
    branches:
      - main

jobs:
  check_generated_code_drift:
    name: Check Generated Code for Drift
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: selefra
        with:
          filters: |
            selefra:
              - '.github/workflows/**/*'

      - name: Install tools
        if: steps.selefra.outputs.selefra == 'true'
        run: |
          bash .github/scripts/terraform.sh
