name: RELEASE

on:
  push:
    branches: 
      - "*"
  # workflow_dispatch:
  #   inputs:
  #     os_version:
  #       required: true
  #       type: string
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ./build/
          key: ${{ runner.OS }}-py-cache-${{ hashFiles('**/README.md') }}
          restore-keys: |
            ${{ runner.OS }}-py-cache-
      - name: build encryption
        run: |
          mkdir build
          touch ./build/123.txt
          cd build && pwd && ls -lh
      - name: Build ${{ inputs.os_version }}
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64
          push: false
          tags: | 
            cdz:nginx
            cdz:nginx