name: RELEASE

on:
  release:
    types: [ created, edited ]
  workflow_dispatch:
    inputs:
      agent_version:
        required: true
        type: string
      server_version:
        required: true
        type: string
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set the value
        id: release
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          ID=`echo ${TAG_NAME##v}`
          if [ -z "${{ inputs.server_version }}" ]
          then
              echo "variable is empty"
          else
              ID=${{ inputs.server_version }}
          fi
          echo "iast_version=$ID" >> $GITHUB_ENV
          
      - name: build encryption
        run: |
          echo ${{ env.iast_version }}
          echo ${{ inputs.agent_version }}
